---
title: "Step 3 - Create a network graph/heatmap/bargraph from square matrix"
author: "Luciano Firpo"
date: '2019-01-21'
output:
  md_document:
    variant: markdown_github
  html_notebook:
    theme: united
    toc: yes
    toc_depth: 3
---


```{r}
#network library
require(visNetwork, quietly = TRUE)
library(reshape)

#we created a mirrored matrix, so we need to clean part of it (lower triangle), otherwise we´ll have duplicated values
new_matrix <- (Product_Matrix)
new_matrix[lower.tri(new_matrix)] <- NA

#View(new_matrix)

#create nodes and edges
nodes <- data.frame(id=colnames(Product_Matrix)[1:ncol(Product_Matrix)])
edges <- (melt(as.matrix(new_matrix)))
colnames(edges) <- c("from","to","value")
#View(nodes)
#View(edges)

#format edges$value to number
edges$value <- as.numeric(edges$value)

#delete NA values
edges <- edges[((!is.na(edges$value)) & edges$value>0),]


nodes$label <- nodes$id
edges$label <- edges$value


net_graph <- visNetwork(nodes, edges,height = "700px", width = "100%") %>%
  visIgraphLayout() %>%
  visNodes(size = 30) %>%
  visOptions(highlightNearest = TRUE,
             nodesIdSelection = TRUE) %>%
  visInteraction(keyboard = TRUE,
                 dragNodes = T, 
                 dragView = T, 
                 zoomView = T)


```

```{r}
#view network graph
net_graph
```

```{r}
#save network graph in html file
htmlwidgets::saveWidget(net_graph, "net_graph.html")
```
```{r}
#matrix bargraph
barplot(Product_Matrix,beside=TRUE, legend=TRUE) 
```

```{r}
library(plotly)

#create a new data frame, to rank the frequency from edges dataframe

df_rank <- edges

#create a new column 'Description' joining columns 'From' and 'To'
df_rank$Description <- ifelse(df_rank$from != df_rank$to, paste(df_rank$from, df_rank$to, sep = " + "), as.character(df_rank$from))

#order dataframe by value
df_rank <- df_rank[order(-df_rank$value),]

#top 10 values
if (nrow(df_rank)>=10){
  df_rank_10 <- df_rank[1:10,]
}else{
  df_rank_10 <- df_rank
}

plot_ly(data = df_rank_10,
     x = ~Description,
     y = ~value,
     type = "bar"
) %>%
layout(
     title = "Frequency rank of product combinations",
     xaxis = list(title = "",
                  categoryorder = "array",
                  categoryarray = ~value,
                  tickangle=-45),
     yaxis = list(title = "Sum of occurrences"),
     margin = list(b = 200)
)

```

```{r}
#heatmap

library(plotly)
 
data=as.matrix(Product_Matrix)

hm1 <- plot_ly(x=colnames(data), y=rownames(data), z = data, type = "heatmap")
 
# with normalization
data=apply(data, 2, function(x){x/mean(x)})
plot_ly(x=colnames(data), y=rownames(data), z = data, type = "heatmap")

```

```{r}
#save network graph in html file
htmlwidgets::saveWidget(hm1, "heatmap1.html")
```


```{r}
#export result
write.csv(df_rank,"Output/rank-combinations.csv")

```
```{r}
library(ggplot2)

df_hm <- df_rank[,(1:3)]

ggplot(data = df_hm, aes(x=from, y=to, fill=value)) + 
  geom_tile()
```
```{r}
#correlation of occurrences

cormat <- round(cor(Product_Matrix),2)
head(cormat)

library(reshape2)
melted_cormat <- melt(cormat)
head(melted_cormat)

library(ggplot2)
ggplot(data = melted_cormat, aes(x=X1, y=X2, fill=value)) + 
  geom_tile()

```

